### ISSUE TITLE
Material icons not showing on Edge  and IE

### ISSUE THREAD

**Issue by dsharew** [dsharew/responsive-miller-column#32]
Icons are not showing on Edge and IE browser, tested on blackberry 

![image](https://cloud.githubusercontent.com/assets/5725548/22457455/95d3e9d4-e7a8-11e6-89de-19e41480c81b.png)
![image](https://cloud.githubusercontent.com/assets/5725548/22457458/9bb22488-e7a8-11e6-8fdd-0ff2c395ddfd.png)

**Comment by maverick42** [comment]
Hi Degen

**OK** with IE11 with latest demo program.
I test on my tablet as soon as possible.

Frédérik

**Comment by maverick42** [comment]
OK for edge !
Good job Degen :)
