### ISSUE TITLE
Material icons not showing on Safari

### ISSUE THREAD

**Issue by dsharew** [dsharew/responsive-miller-column#33]
Tested on blackberry device, safari browser (v: 10.9.5)
![image](https://cloud.githubusercontent.com/assets/5725548/22457213/910b2cc4-e7a7-11e6-9977-bcc3cc440954.png)

**Comment by maverick42** [comment]
Hi Degen

http://caniuse.com/#feat=woff2

I tested you demo program on : 
- PC/W7 : Old safari browser (5.1.7) : NOK
- IMac/Sierra : **OK**
- IPhone 4S: **OK**
- IPhone 6 : **OK**

==> On safari browser it's OK :)

Frédérik

**Comment by maverick42** [comment]
Hi Degen

On PC :

- latest Chrome : **OK**
- latest Opera : **OK**
- latest Firefox : **OK**
- IE11 : **OK**

On Mobile Blackberry Passport  :

- internal browser (webkit safari ?) : NOK
- Opera : **OK**

**Comment by maverick42** [comment]
On IPAD : OK

**Comment by dsharew** [comment]
@maverick42  This very important info, we need to put it somewhere on the plugin page.
