### ISSUE TITLE
Are you able to publish this library to a dependency tool?

### ISSUE THREAD

**Issue by btanabe** [dsharew/responsive-miller-column#40]
Hello, it would be great if this library was published to npm/bower?

Thanks,
Brian.

**Comment by dsharew** [comment]
@btanabe I would be happy if you can help with that I am not js developer now it will take me some time to do this :)

**Comment by dsharew** [comment]
@yonashailug could please help here?

**Comment by dsharew** [comment]
just published version 1.0.0 to https://www.npmjs.com/package/responsive-miller-column :)
